"""add index

Revision ID: 82ae0fe9db8c
Revises: 1dcce2adc986
Create Date: 2026-07-25 22:55:15.072937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ae0fe9db8c'
down_revision: Union[str, Sequence[str], None] = '1dcce2adc986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_customer_id', 'orders', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_customer_id', table_name='orders')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    # ### end Alembic commands ###
